/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lambda.with.Api.Gateway;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
